name: Package and release

on:
  push:
    tags:
      - '**'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Package and release the retail version
      - name: Create Retail Package
        uses: BigWigsMods/packager@v2

      # Package and release the Classic version
      - name: Create Classic Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g classic

      # Package and release the wrath version
      # - name: Create Wrath Package
      #   uses: BigWigsMods/packager@v2
      #   with:
      #     args: -g wrath

       # Package and release the Cata version
      - name: Create Cata Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g Cata